name: forams
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy=1.25.2
  - pandas=1.5.3
  - pillow=11.3.0
  - scikit-learn=1.3.1
  - tqdm=4.66.1
  - pip:
      - matplotlib==3.7.2
      - seaborn==0.11.2
      - torch==2.7.1
      - torchvision==0.22.1